import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthContextProvider from "@/lib/api-handler/auth-contex";
import RecipeContexProvider from "@/lib/api-handler/recipeHandler";
import NavBar from "@/components/navBar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Recipe Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <RecipeContexProvider>
            <ToastContainer />
            <NavBar />
            {children}
          </RecipeContexProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
